facts = [
    "Fun Fact: Rats did not spread the plague. This is misinfo spread by rat haters!",
    "Fun Fact: This game was not tested with actual rats. Their hands are too small to press the buttons. :(",
    "Fun Fact: Rats can run at up to 7mph. Therefore this game is realistic!",
    "Fun Fact: This is the forth fun fact stored in the list of fun facts!",
    "Fun Fact: I think the rat is named Dave.",
    "Fun Fact: This is a video game!",
    "Fun Fact: Rats exist in real life, woah!",
    "Fun Fact: You don't know that there isn't a rat hunting you down as you read this...",
    "Fun Fact: Press the jump button to jump. Well not right now. You can't jump on the loading screen.",
    "Fun Fact: Computer Science is the only science that does not have anything to do with rats.", 
    "Fun Fact: The button prompts were made by \"Nicolae (Xelu) Berbece\".",
    "Fun Fact: RAT!!1!!!!1!!!111!!111!!!111",
    "Fun Fact: .rat() is not a function in this game. But it should be.",
    "Fun Fact: There are at least 5 rats at any time!",
    "Fun Fact: This game will probably never come out since I spend more time adding facts than coding the game.",
    "Fun Fact: The rat is really fast.",
    "Fun Fact: It is 12:40am on the 31st of July 2024 as I am typing this.",
    "Fun Fact: I am putting way too much effort into a game 5 people will play for 5 minutes!",
    "Fun Fact: Some levels will load faster than you can read the fun fact. What a shame..."
]